export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CREATE_RECORD_REQUEST = "CREATE_RECORD_REQUEST";
export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS";
export const CREATE_RECORD_RESET = "CREATE_RECORD_RESET";
export const CREATE_RECORD_FAIL = "CREATE_RECORD_FAIL";

export const ALL_RECORDS_REQUEST = "ALL_RECORDS_REQUEST";
export const ALL_RECORDS_SUCCESS = "ALL_RECORDS_SUCCESS";
export const ALL_RECORDS_FAIL = "ALL_RECORDS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_RECORD_REQUEST = "DELETE_RECORD_REQUEST";
export const DELETE_RECORD_SUCCESS = "DELETE_RECORD_SUCCESS";
export const DELETE_RECORD_RESET = "DELETE_RECORD_RESET"
export const DELETE_RECORD_FAIL = "DELETE_RECORD_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
